logging:
  local_writer:
    max_log_size: 0
  max_buffer_size: 20
  steps_per_log: 10

machine:
  seed: 42
  
mixed_precision: false
output_dir: outputs
steps_per_eval_batch: 500
steps_per_eval_image: 2000
steps_per_save: 2000

pipeline:
  datamanager:
    train_cameras_sampling_strategy: random
    train_cameras_sampling_seed: 42
    cache_images: gpu
  model:
    refine_start: 500
    refine_every: 100
    resolution_schedule: 3000
    background_color: white
    num_downscales: 2
    continue_cull_post_densification: True
    reset_alpha_every: 30
    n_split_samples: 2
    sh_degree_interval: 1000
    ssim_lambda: 0.2
    sh_degree: 3
    use_scale_regularization: False
    max_gauss_ratio: 10.0
    output_depth_during_training: False
    rasterize_mode: classic
    use_bilateral_grid: False
    grid_shape: [16, 16, 8]
    color_corrected_metrics: False


dataparser:
  orientation_method: none
  eval_mode: interval
  eval_interval: 2
  scale_factor: 1.0

